"""create games table

Revision ID: 97ba17a91133
Revises: ccfb78a9112c
Create Date: 2026-09-20 11:57:51.585187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ba17a91133'
down_revision: Union[str, Sequence[str], None] = 'ccfb78a9112c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('developer', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.create_index(op.f('ix_games_slug'), 'games', ['slug'], unique=True)
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.drop_index(op.f('ix_games_slug'), table_name='games')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
